language: node_js
node_js:
  - "stable"
install:
    - npm install
script:
  - npm cover
cache:
  directories:
   - "node_modules"
deploy:
  skip_cleanup: true
  local_dir: build
after_success:
  - npm run coveralls